# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']

    sonata.admin.business:
        class: AppBundle\Admin\BusinessAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Business" }
        arguments:
            - ~
            - AppBundle\Entity\Business
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle]]

    sonata.admin.city:
        class: AppBundle\Admin\CityAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Geography", label: "City" }
        arguments:
            - ~
            - AppBundle\Entity\City
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle]]
